import 'dart:convert';

import 'package:flutter/cupertino.dart';
import 'package:http/http.dart' as http;
import 'Autogenerated.dart';

class ProductProvider extends ChangeNotifier{

  List<Autogenerated> _autogenerated = [];


  Future<List<Autogenerated>> getProduct() async {
    var url = Uri.parse("https://api.escuelajs.co/api/v1/products");
    final response = await http.get(url);
    if (response.statusCode == 200) {
      dynamic jsonResponse = jsonDecode(response.body);
      _autogenerated = List<Autogenerated>.from(jsonResponse.map((data)=> Autogenerated.fromJson(data))).toList();
    } else {
      return [];
    }
    notifyListeners();

    return _autogenerated;

  }
}